#  {
#       "type": "Microsoft.Compute/virtualMachines/extensions",
#       "name": "[concat(parameters('vmName'),'/', parameters('vmExtensionName'))]",
#       "apiVersion": "2015-05-01-preview",
#       "location": "[parameters('location')]",
#       "dependsOn": [
#         "[concat('Microsoft.Compute/virtualMachines/', parameters('vmName'))]"
#       ],
#       "properties": {
#         "publisher": "Microsoft.Azure.Security",
#         "type": "IaaSAntimalware",
#         "typeHandlerVersion": "1.1",
#         "settings": {
#           "AntimalwareEnabled": "true",
#           "Exclusions": {
#             "Paths": "C:\\Users",
#             "Extensions": ".txt",
#             "Processes": "taskmgr.exe"
#           },
#           "RealtimeProtectionEnabled": "true",
#           "ScheduledScanSettings": {
#             "isEnabled": "true",
#             "scanType": "Quick",
#             "day": "7",
#             "time": "120"
#           }
#         },
#         "protectedSettings": null
#       }
#   }


- name: Configure Antimalware for Windows VMs
  hosts: "{{ var_hosts }}"
  gather_facts: no
  connection: local

  vars:
    exclude_paths: "{{ antimalware_exclude_paths }}"
    exclude_extentions: "{{ antimalware_exclude_extentions }}"
    exclude_processes: "{{ antimalware_exclude_processes }}"
    schedule_scan_enabled: "{{ antimalware_schedule_scan_enabled }}"
    schedule_scan_type: "{{ antimalware_schedule_scan_type }}"
    schedule_scan_date: "{{ antimalware_schedule_scan_day }}"
    schedule_scan_time: "{{ antimalware_schedule_scan_time }}"
    RealtimeProtectionEnabled: "{{ antimalware_RealtimeProtectionEnabled }}"
    AntimalwareEnabled : "true"

  tasks:

    - name: Build the public settings 
      set_fact: 
        antimalware_public_settings: '{
            "AntimalwareEnabled": "{{ AntimalwareEnabled }}",
            "Exclusions": {
              "Paths": "{{ exclude_paths }}",
              "Extensions": "{{ exclude_extentions }}",
              "Processes": "{{ exclude_processes }}"
            },
            "RealtimeProtectionEnabled": "{{ RealtimeProtectionEnabled }}",
            "ScheduledScanSettings": {
              "isEnabled": "{{ schedule_scan_enabled }}",
              "scanType": "{{ schedule_scan_type }}",
              "day": "{{ schedule_scan_date }}",
              "time": "{{ schedule_scan_time }}"
            }
          }'
   

    - name: Build the protected settings 
      set_fact: 
        antimalware_protected_settings: '{ 

        }'

    - name: Tell Azure to install and enable the JsonADDomainExtension extension 
      include_tasks: ../../tasks/az-wrappers/az-vm-extension-set.yml
      with_items:      
        - { 
            'publisher': "Microsoft.Azure.Security",
            'name': "IaaSAntimalware",
            'version': "1.1",
            'resource-group': "{{ vm_resource_group }}",
            'vm-name': "{{ vm_name }}",
            'protected-settings': "{{ antimalware_protected_settings }}",
            'settings': "{{ antimalware_public_settings }}"
          }
    - set_fact:
        vm_extension_set : "{{ az_vm_extension_set.output }}"  

    - name: Print  results
      debug:
        msg: "todo"  
    